# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caso.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='caso.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ncaso.proto\x12\x04main\",\n\x0b\x43\x61soRequest\x12\x1d\n\x05\x63\x61sos\x18\x01 \x03(\x0b\x32\x0e.main.CasoItem\"f\n\x08\x43\x61soItem\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65partamento\x18\x02 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x03 \x01(\x05\x12\x16\n\x0e\x66orma_contagio\x18\x04 \x01(\t\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\"\x1c\n\tCasoReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2:\n\x04\x43\x61so\x12\x32\n\nCrearCasos\x12\x11.main.CasoRequest\x1a\x0f.main.CasoReply\"\x00\x62\x06proto3'
)




_CASOREQUEST = _descriptor.Descriptor(
  name='CasoRequest',
  full_name='main.CasoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='casos', full_name='main.CasoRequest.casos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)


_CASOITEM = _descriptor.Descriptor(
  name='CasoItem',
  full_name='main.CasoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='main.CasoItem.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='departamento', full_name='main.CasoItem.departamento', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edad', full_name='main.CasoItem.edad', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forma_contagio', full_name='main.CasoItem.forma_contagio', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estado', full_name='main.CasoItem.estado', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=168,
)


_CASOREPLY = _descriptor.Descriptor(
  name='CasoReply',
  full_name='main.CasoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='main.CasoReply.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=198,
)

_CASOREQUEST.fields_by_name['casos'].message_type = _CASOITEM
DESCRIPTOR.message_types_by_name['CasoRequest'] = _CASOREQUEST
DESCRIPTOR.message_types_by_name['CasoItem'] = _CASOITEM
DESCRIPTOR.message_types_by_name['CasoReply'] = _CASOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CasoRequest = _reflection.GeneratedProtocolMessageType('CasoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CASOREQUEST,
  '__module__' : 'caso_pb2'
  # @@protoc_insertion_point(class_scope:main.CasoRequest)
  })
_sym_db.RegisterMessage(CasoRequest)

CasoItem = _reflection.GeneratedProtocolMessageType('CasoItem', (_message.Message,), {
  'DESCRIPTOR' : _CASOITEM,
  '__module__' : 'caso_pb2'
  # @@protoc_insertion_point(class_scope:main.CasoItem)
  })
_sym_db.RegisterMessage(CasoItem)

CasoReply = _reflection.GeneratedProtocolMessageType('CasoReply', (_message.Message,), {
  'DESCRIPTOR' : _CASOREPLY,
  '__module__' : 'caso_pb2'
  # @@protoc_insertion_point(class_scope:main.CasoReply)
  })
_sym_db.RegisterMessage(CasoReply)



_CASO = _descriptor.ServiceDescriptor(
  name='Caso',
  full_name='main.Caso',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=200,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='CrearCasos',
    full_name='main.Caso.CrearCasos',
    index=0,
    containing_service=None,
    input_type=_CASOREQUEST,
    output_type=_CASOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASO)

DESCRIPTOR.services_by_name['Caso'] = _CASO

# @@protoc_insertion_point(module_scope)
