# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message.caso_pb2 as caso__pb2


class CasoStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearCaso = channel.unary_unary(
                '/main.Caso/CrearCaso',
                request_serializer=caso__pb2.CasoRequest.SerializeToString,
                response_deserializer=caso__pb2.CasoReply.FromString,
                )


class CasoServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CrearCaso(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CasoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearCaso': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearCaso,
                    request_deserializer=caso__pb2.CasoRequest.FromString,
                    response_serializer=caso__pb2.CasoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Caso', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Caso(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CrearCaso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Caso/CrearCaso',
            caso__pb2.CasoRequest.SerializeToString,
            caso__pb2.CasoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
